In [19]:
import pandas as pd

In [20]:
TSLA_yr2019News_FullArtciles_df = pd.read_csv('./data/TSLA_yr2019News_FullArtciles_df.csv')

In [21]:
TSLA_yr2019News_FullArtciles_df.tail(2)

,Unnamed: 0,news_url,image_url,title,text,source_name,date,topics,sentiment,type,tickers,full_text
288,288,https://www.zacks.com/stock/news/619555/tesla-...,https://cdn.snapi.dev/images/v1/o/j/tes723-5.jpg,Tesla (TSLA) to Open First European Gigafactor...,Car production in Tesla's (TSLA) Berlin Gigafa...,Zacks Investment Research,14 Nov 2019,[],Neutral,Article,['TSLA'],Tesla ’s (TSLA - Free Report) electric revolut...
289,289,https://www.fool.com/investing/2019/11/13/here...,https://cdn.snapi.dev/images/v1/n/f/105762111-...,Here's Why Tesla Bears Should Be Concerned,It's understandable if bears are getting worri...,The Motley Fool,13 Nov 2019,[],Negative,Article,['TSLA'],Tesla (NASDAQ:TSLA) bears have reason to worry...

In [32]:
# create custom df from the main df
TSLA_Custom_df=  TSLA_yr2019News_FullArtciles_df[['date', 'title', 'text','full_text',
       'source_name', 'sentiment', 'tickers']]

In [33]:
# replace sentiment column values with new value set
sentiment_map = {"Positive": 1, "Negative": -1, "Neutral": 0}
TSLA_Custom_df["sentiment"].replace(sentiment_map, inplace=True)

C:\Users\JATIN\anaconda3\lib\site-packages\pandas\core\generic.py:6746: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

In [34]:
TSLA_Custom_df.head(2)

,date,title,text,full_text,source_name,sentiment,tickers
0,31 Dec 2019,Why the Stock Market Soured on Tesla and Centu...,The carmaker's CEO had some Boring news to rep...,Many of us are preparing for the new year and ...,The Motley Fool,-1,"['CTL', 'TSLA']"
1,30 Dec 2019,Tesla to Start Delivery of Model 3 Built at Ch...,The construction of Gigafactory3 in Shanghai i...,"Tesla, Inc. (TSLA - Free Report) will start de...",Zacks Investment Research,0,['TSLA']

In [35]:
# change data type of date column and set it as index
TSLA_Custom_df = TSLA_Custom_df.astype({"date": 'datetime64'})
TSLA_Custom_df.set_index("date", inplace=True)

In [36]:
TSLA_Custom_df.head(2)

,title,text,full_text,source_name,sentiment,tickers
date,,,,,,
2019-12-31,Why the Stock Market Soured on Tesla and Centu...,The carmaker's CEO had some Boring news to rep...,Many of us are preparing for the new year and ...,The Motley Fool,-1,"['CTL', 'TSLA']"
2019-12-30,Tesla to Start Delivery of Model 3 Built at Ch...,The construction of Gigafactory3 in Shanghai i...,"Tesla, Inc. (TSLA - Free Report) will start de...",Zacks Investment Research,0,['TSLA']

In [37]:
# Because this dataframe contains records related to ticker TSLA only, rename 'tickers' coulmn as 'ticker' and set its value as TSLA for all records
TSLA_Custom_df.rename(columns={"tickers": "ticker"}, inplace=True)
TSLA_Custom_df["ticker"]="TSLA"

# also rename sentiment column to 'stocknews_sentiment' 
TSLA_Custom_df.rename(columns={"sentiment": "stocknews_sentiment"}, inplace=True)

In [38]:
TSLA_Custom_df.head(2)

,title,text,full_text,source_name,stocknews_sentiment,ticker
date,,,,,,
2019-12-31,Why the Stock Market Soured on Tesla and Centu...,The carmaker's CEO had some Boring news to rep...,Many of us are preparing for the new year and ...,The Motley Fool,-1,TSLA
2019-12-30,Tesla to Start Delivery of Model 3 Built at Ch...,The construction of Gigafactory3 in Shanghai i...,"Tesla, Inc. (TSLA - Free Report) will start de...",Zacks Investment Research,0,TSLA

In [39]:
# create dataframe for machine learning
ml_df=pd.DataFrame(TSLA_Custom_df.groupby(["date","source_name","ticker"])["stocknews_sentiment"].mean())

In [40]:
ml_df

                                             stocknews_sentiment
date       source_name               ticker
2019-03-06 The Motley Fool           TSLA                    0.0
2019-03-08 Zacks Investment Research TSLA                    1.0
2019-03-09 The Motley Fool           TSLA                   -1.0
2019-03-11 The Motley Fool           TSLA                   -1.0
2019-03-12 The Motley Fool           TSLA                   -1.0
...                                                          ...
2019-12-27 Zacks Investment Research TSLA                    1.0
2019-12-28 The Motley Fool           TSLA                    1.0
2019-12-29 The Motley Fool           TSLA                    0.0
2019-12-30 Zacks Investment Research TSLA                    0.5
2019-12-31 The Motley Fool           TSLA                   -1.0

[200 rows x 1 columns]

In [41]:
ml_df.to_csv('./data/ml_df.csv',  header=ml_df.columns)