In [1]:
import pandas as pd

In [2]:
TSLA_yr2019News_FullArtciles_df = pd.read_csv('./data/TSLA_yr2019News_FullArtciles_df.csv')

In [3]:
TSLA_yr2019News_FullArtciles_df.tail(2)

,Unnamed: 0,news_url,image_url,title,text,source_name,date,topics,sentiment,type,tickers,full_text
288,288,https://www.zacks.com/stock/news/619555/tesla-...,https://cdn.snapi.dev/images/v1/o/j/tes723-5.jpg,Tesla (TSLA) to Open First European Gigafactor...,Car production in Tesla's (TSLA) Berlin Gigafa...,Zacks Investment Research,14 Nov 2019,[],Neutral,Article,['TSLA'],Tesla ’s (TSLA - Free Report) electric revolut...
289,289,https://www.fool.com/investing/2019/11/13/here...,https://cdn.snapi.dev/images/v1/n/f/105762111-...,Here's Why Tesla Bears Should Be Concerned,It's understandable if bears are getting worri...,The Motley Fool,13 Nov 2019,[],Negative,Article,['TSLA'],Tesla (NASDAQ:TSLA) bears have reason to worry...

In [4]:
# create custom df from the main df
TSLA_Custom_df=  TSLA_yr2019News_FullArtciles_df[['date', 'title', 'text','full_text',
       'source_name', 'sentiment', 'tickers']]

In [5]:
# replace sentiment column values with new value set
sentiment_map = {"Positive": 1, "Negative": -1, "Neutral": 0}
TSLA_Custom_df["sentiment"].replace(sentiment_map, inplace=True)

C:\Users\JATIN\anaconda3\lib\site-packages\pandas\core\generic.py:6746: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

In [6]:
TSLA_Custom_df.head(2)

,date,title,text,full_text,source_name,sentiment,tickers
0,31 Dec 2019,Why the Stock Market Soured on Tesla and Centu...,The carmaker's CEO had some Boring news to rep...,Many of us are preparing for the new year and ...,The Motley Fool,-1,"['CTL', 'TSLA']"
1,30 Dec 2019,Tesla to Start Delivery of Model 3 Built at Ch...,The construction of Gigafactory3 in Shanghai i...,"Tesla, Inc. (TSLA - Free Report) will start de...",Zacks Investment Research,0,['TSLA']

In [7]:
# change data type of date column and set it as index
TSLA_Custom_df = TSLA_Custom_df.astype({"date": 'datetime64'})
TSLA_Custom_df.set_index("date", inplace=True)

In [8]:
TSLA_Custom_df

,title,text,full_text,source_name,sentiment,tickers
date,,,,,,
2019-12-31,Why the Stock Market Soured on Tesla and Centu...,The carmaker's CEO had some Boring news to rep...,Many of us are preparing for the new year and ...,The Motley Fool,-1,"['CTL', 'TSLA']"
2019-12-30,Tesla to Start Delivery of Model 3 Built at Ch...,The construction of Gigafactory3 in Shanghai i...,"Tesla, Inc. (TSLA - Free Report) will start de...",Zacks Investment Research,0,['TSLA']
2019-12-30,Tesla (TSLA) Rolls Out First Model 3s Built in...,Tesla Motors (TSLA) remains near the peak of i...,"Monday, December 30, 2019\nAdvance Trade in U....",Zacks Investment Research,1,['TSLA']
2019-12-29,How Many Vehicles Will Tesla Deliver in Q4?,The company is slated to report its quarterly ...,Sometime this week -- probably on Thursday or ...,The Motley Fool,0,['TSLA']
2019-12-28,Why Your 2020 Resolution Should Be to Buy More...,"After a great 2019 capstone to the 2010s, tech...",After a decade of virtually no returns -- than...,The Motley Fool,1,"['AMZN', 'GOOG', 'GOOGL', 'MSFT', 'NFLX', 'TSL..."
...,...,...,...,...,...,...
2019-11-16,What We Know About Tesla's Pickup Truck,The electric-car company will finally unveil t...,As if electric-car maker Tesla (NASDAQ:TSLA) i...,The Motley Fool,0,['TSLA']
2019-11-15,"""Consumer Reports"" Now Recommends Tesla's Mode...",The news comes as Tesla aims for record delive...,In a reversal of a previous decision not to re...,The Motley Fool,1,['TSLA']
2019-11-15,3 Stocks That Soared This Earnings Season,Don't miss the stories behind these companies'...,"As usual, earnings season brought with it its ...",The Motley Fool,1,"['AAPL', 'DIS', 'TSLA']"
2019-11-14,Tesla (TSLA) to Open First European Gigafactor...,Car production in Tesla's (TSLA) Berlin Gigafa...,Tesla ’s (TSLA - Free Report) electric revolut...,Zacks Investment Research,0,['TSLA']
2019-11-13,Here's Why Tesla Bears Should Be Concerned,It's understandable if bears are getting worri...,Tesla (NASDAQ:TSLA) bears have reason to worry...,The Motley Fool,-1,['TSLA']

In [9]:
# Because this dataframe contains records related to ticker TSLA only, rename 'tickers' coulmn as 'ticker' and set its value as TSLA for all records
TSLA_Custom_df.rename(columns={"tickers": "ticker"}, inplace=True)
TSLA_Custom_df["ticker"]="TSLA"

# also rename sentiment column to 'stocknews_sentiment' 
TSLA_Custom_df.rename(columns={"sentiment": "stocknews_sentiment"}, inplace=True)

In [10]:
TSLA_Custom_df.head(2)

,title,text,full_text,source_name,stocknews_sentiment,ticker
date,,,,,,
2019-12-31,Why the Stock Market Soured on Tesla and Centu...,The carmaker's CEO had some Boring news to rep...,Many of us are preparing for the new year and ...,The Motley Fool,-1,TSLA
2019-12-30,Tesla to Start Delivery of Model 3 Built at Ch...,The construction of Gigafactory3 in Shanghai i...,"Tesla, Inc. (TSLA - Free Report) will start de...",Zacks Investment Research,0,TSLA

In [11]:
# create dataframe for machine learning grouped by ["date","source_name","ticker"]
ml_df=pd.DataFrame(TSLA_Custom_df.groupby(["date","source_name","ticker"])["stocknews_sentiment"].mean())

In [12]:
ml_df

                                             stocknews_sentiment
date       source_name               ticker
2019-03-06 The Motley Fool           TSLA                    0.0
2019-03-08 Zacks Investment Research TSLA                    1.0
2019-03-09 The Motley Fool           TSLA                   -1.0
2019-03-11 The Motley Fool           TSLA                   -1.0
2019-03-12 The Motley Fool           TSLA                   -1.0
...                                                          ...
2019-12-27 Zacks Investment Research TSLA                    1.0
2019-12-28 The Motley Fool           TSLA                    1.0
2019-12-29 The Motley Fool           TSLA                    0.0
2019-12-30 Zacks Investment Research TSLA                    0.5
2019-12-31 The Motley Fool           TSLA                   -1.0

[200 rows x 1 columns]

In [13]:
ml_df.to_csv('./data/ml_df.csv',  header=ml_df.columns)

In [14]:
# create dataframe for machine learning grouped by ["date","ticker"]
ml_df_stocknews=TSLA_Custom_df

In [15]:
ml_df_stocknews

,title,text,full_text,source_name,stocknews_sentiment,ticker
date,,,,,,
2019-12-31,Why the Stock Market Soured on Tesla and Centu...,The carmaker's CEO had some Boring news to rep...,Many of us are preparing for the new year and ...,The Motley Fool,-1,TSLA
2019-12-30,Tesla to Start Delivery of Model 3 Built at Ch...,The construction of Gigafactory3 in Shanghai i...,"Tesla, Inc. (TSLA - Free Report) will start de...",Zacks Investment Research,0,TSLA
2019-12-30,Tesla (TSLA) Rolls Out First Model 3s Built in...,Tesla Motors (TSLA) remains near the peak of i...,"Monday, December 30, 2019\nAdvance Trade in U....",Zacks Investment Research,1,TSLA
2019-12-29,How Many Vehicles Will Tesla Deliver in Q4?,The company is slated to report its quarterly ...,Sometime this week -- probably on Thursday or ...,The Motley Fool,0,TSLA
2019-12-28,Why Your 2020 Resolution Should Be to Buy More...,"After a great 2019 capstone to the 2010s, tech...",After a decade of virtually no returns -- than...,The Motley Fool,1,TSLA
...,...,...,...,...,...,...
2019-11-16,What We Know About Tesla's Pickup Truck,The electric-car company will finally unveil t...,As if electric-car maker Tesla (NASDAQ:TSLA) i...,The Motley Fool,0,TSLA
2019-11-15,"""Consumer Reports"" Now Recommends Tesla's Mode...",The news comes as Tesla aims for record delive...,In a reversal of a previous decision not to re...,The Motley Fool,1,TSLA
2019-11-15,3 Stocks That Soared This Earnings Season,Don't miss the stories behind these companies'...,"As usual, earnings season brought with it its ...",The Motley Fool,1,TSLA
2019-11-14,Tesla (TSLA) to Open First European Gigafactor...,Car production in Tesla's (TSLA) Berlin Gigafa...,Tesla ’s (TSLA - Free Report) electric revolut...,Zacks Investment Research,0,TSLA
2019-11-13,Here's Why Tesla Bears Should Be Concerned,It's understandable if bears are getting worri...,Tesla (NASDAQ:TSLA) bears have reason to worry...,The Motley Fool,-1,TSLA

In [27]:
ml_df_stocknews.to_csv('./data/ml_df_stocknews.csv',  header=ml_df_stocknews.columns)

In [28]:
## Pull TSLA stock prices and create a dataframe for year 2019

In [29]:
import yfinance as yf

In [30]:
# get TSLA historical market data

tsla_df = yf.download("TSLA", start="2018-12-31", end="2020-01-01")

[*********************100%***********************]  1 of 1 completed

In [31]:
tsla_df=tsla_df[["Close"]]

In [32]:
tsla_df["Close_shifted_by_1"] = tsla_df.Close.shift(1)
tsla_df=tsla_df[tsla_df.index.year == 2019]

C:\Users\JATIN\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [33]:
#tsla_df.columns=['TSLA_Close', 'TSLA_Close_shifted_by_1']

In [34]:
tsla_df.reset_index(inplace=True)
tsla_df.columns

Index(['Date', 'Close', 'Close_shifted_by_1'], dtype='object')

In [35]:
tsla_df.columns=['date','TSLA_close', 'TSLA_close_shifted_by_1']
tsla_df.head(2)

        date  TSLA_close  TSLA_close_shifted_by_1
0 2019-01-02  310.119995               332.799988
1 2019-01-03  300.359985               310.119995

In [36]:
tsla_df.set_index("date", inplace=True)

In [37]:
tsla_df.head(3)

            TSLA_close  TSLA_close_shifted_by_1
date
2019-01-02  310.119995               332.799988
2019-01-03  300.359985               310.119995
2019-01-04  317.690002               300.359985

## Import ml_df_stocknews.csv and create a dataframe for regression analysis. Then import vader sentiments into it.

In [38]:
tsla_df.to_csv('./data/tsla_df.csv',  header=tsla_df.columns)

In [39]:
df_for_regression = pd.read_csv('./data/ml_df_stocknews.csv', parse_dates=True)

In [42]:
df_for_regression

,date,title,text,full_text,source_name,stocknews_sentiment,ticker
0,2019-12-31,Why the Stock Market Soured on Tesla and Centu...,The carmaker's CEO had some Boring news to rep...,Many of us are preparing for the new year and ...,The Motley Fool,-1,TSLA
1,2019-12-30,Tesla to Start Delivery of Model 3 Built at Ch...,The construction of Gigafactory3 in Shanghai i...,"Tesla, Inc. (TSLA - Free Report) will start de...",Zacks Investment Research,0,TSLA
2,2019-12-30,Tesla (TSLA) Rolls Out First Model 3s Built in...,Tesla Motors (TSLA) remains near the peak of i...,"Monday, December 30, 2019\nAdvance Trade in U....",Zacks Investment Research,1,TSLA
3,2019-12-29,How Many Vehicles Will Tesla Deliver in Q4?,The company is slated to report its quarterly ...,Sometime this week -- probably on Thursday or ...,The Motley Fool,0,TSLA
4,2019-12-28,Why Your 2020 Resolution Should Be to Buy More...,"After a great 2019 capstone to the 2010s, tech...",After a decade of virtually no returns -- than...,The Motley Fool,1,TSLA
...,...,...,...,...,...,...,...
285,2019-11-16,What We Know About Tesla's Pickup Truck,The electric-car company will finally unveil t...,As if electric-car maker Tesla (NASDAQ:TSLA) i...,The Motley Fool,0,TSLA
286,2019-11-15,"""Consumer Reports"" Now Recommends Tesla's Mode...",The news comes as Tesla aims for record delive...,In a reversal of a previous decision not to re...,The Motley Fool,1,TSLA
287,2019-11-15,3 Stocks That Soared This Earnings Season,Don't miss the stories behind these companies'...,"As usual, earnings season brought with it its ...",The Motley Fool,1,TSLA
288,2019-11-14,Tesla (TSLA) to Open First European Gigafactor...,Car production in Tesla's (TSLA) Berlin Gigafa...,Tesla ’s (TSLA - Free Report) electric revolut...,Zacks Investment Research,0,TSLA
289,2019-11-13,Here's Why Tesla Bears Should Be Concerned,It's understandable if bears are getting worri...,Tesla (NASDAQ:TSLA) bears have reason to worry...,The Motley Fool,-1,TSLA

## Read in Vader, textblob lemmatized sentiments, textblob stemmed sentiments data for the news articlesand create the final dataframe to run regression on.

In [43]:
df_vader_sentiments = pd.read_csv('./data/vader_sentiments.csv',usecols=['Compound'])

In [44]:
df_vader_sentiments.head(3)

   Compound
0    0.9109
1    0.9961
2   -0.8271

In [45]:
df_for_regression["vader_sentiment"] =  list(df_vader_sentiments["Compound"])

In [46]:
df_textblob_lemmatized_sentiments = pd.read_csv('./data/textblob_lemmatized_sentiments.csv',usecols=['full_text'])

In [47]:
df_textblob_lemmatized_sentiments.head(3)

   full_text
0   0.087333
1   0.028692
2   0.078244

In [48]:
df_for_regression["textblob_lemmatized_sentiments"] = list(df_textblob_lemmatized_sentiments["full_text"])

In [49]:
df_textblob_stemmed_sentiments = pd.read_csv('./data/textblob_stemmed_sentiments.csv',usecols=['full_text'])

In [50]:
df_textblob_stemmed_sentiments.head(3)

   full_text
0   0.112693
1  -0.029774
2   0.099321

In [51]:
df_for_regression["textblob_stemmed_sentiments"] = list(df_textblob_stemmed_sentiments["full_text"])

In [52]:
df_for_regression

,date,title,text,full_text,source_name,stocknews_sentiment,ticker,vader_sentiment,textblob_lemmatized_sentiments,textblob_stemmed_sentiments
0,2019-12-31,Why the Stock Market Soured on Tesla and Centu...,The carmaker's CEO had some Boring news to rep...,Many of us are preparing for the new year and ...,The Motley Fool,-1,TSLA,0.9109,0.087333,0.112693
1,2019-12-30,Tesla to Start Delivery of Model 3 Built at Ch...,The construction of Gigafactory3 in Shanghai i...,"Tesla, Inc. (TSLA - Free Report) will start de...",Zacks Investment Research,0,TSLA,0.9961,0.028692,-0.029774
2,2019-12-30,Tesla (TSLA) Rolls Out First Model 3s Built in...,Tesla Motors (TSLA) remains near the peak of i...,"Monday, December 30, 2019\nAdvance Trade in U....",Zacks Investment Research,1,TSLA,-0.8271,0.078244,0.099321
3,2019-12-29,How Many Vehicles Will Tesla Deliver in Q4?,The company is slated to report its quarterly ...,Sometime this week -- probably on Thursday or ...,The Motley Fool,0,TSLA,0.9880,0.119706,0.023636
4,2019-12-28,Why Your 2020 Resolution Should Be to Buy More...,"After a great 2019 capstone to the 2010s, tech...",After a decade of virtually no returns -- than...,The Motley Fool,1,TSLA,0.9934,0.100860,0.057399
...,...,...,...,...,...,...,...,...,...,...
285,2019-11-16,What We Know About Tesla's Pickup Truck,The electric-car company will finally unveil t...,As if electric-car maker Tesla (NASDAQ:TSLA) i...,The Motley Fool,0,TSLA,0.9811,0.075481,0.091288
286,2019-11-15,"""Consumer Reports"" Now Recommends Tesla's Mode...",The news comes as Tesla aims for record delive...,In a reversal of a previous decision not to re...,The Motley Fool,1,TSLA,0.9850,0.193791,0.028636
287,2019-11-15,3 Stocks That Soared This Earnings Season,Don't miss the stories behind these companies'...,"As usual, earnings season brought with it its ...",The Motley Fool,1,TSLA,0.9962,0.174148,0.159366
288,2019-11-14,Tesla (TSLA) to Open First European Gigafactor...,Car production in Tesla's (TSLA) Berlin Gigafa...,Tesla ’s (TSLA - Free Report) electric revolut...,Zacks Investment Research,0,TSLA,0.9947,0.103478,0.091447
289,2019-11-13,Here's Why Tesla Bears Should Be Concerned,It's understandable if bears are getting worri...,Tesla (NASDAQ:TSLA) bears have reason to worry...,The Motley Fool,-1,TSLA,0.9947,0.104454,0.061764

In [53]:
# df_for_regression.reset_index(inplace=True)

In [54]:
df_for_regression=df_for_regression.astype({'date': 'datetime64[ns]'})

In [55]:
df_for_regression.dtypes

date                              datetime64[ns]
title                                     object
text                                      object
full_text                                 object
source_name                               object
stocknews_sentiment                        int64
ticker                                    object
vader_sentiment                          float64
textblob_lemmatized_sentiments           float64
textblob_stemmed_sentiments              float64
dtype: object

In [56]:
df_for_regression.set_index("date", inplace=True)

### remember - _row 143 is invalid, remove it_

In [57]:
df_for_regression["vader_sentiment"][143]

-0.2023

In [58]:
df_for_regression=df_for_regression.sort_values("date", ascending=True)

In [60]:
df_for_regression

,title,text,full_text,source_name,stocknews_sentiment,ticker,vader_sentiment,textblob_lemmatized_sentiments,textblob_stemmed_sentiments
date,,,,,,,,,
2019-03-06,Did Audi Just Disrupt Tesla's Model Y?,Audi's e-tron Q4 Concept is aimed squarely at ...,Audi AG (OTC:AUDV.F) took the wraps off its la...,The Motley Fool,0,TSLA,0.9726,0.069364,0.041566
2019-03-08,Tesla (TSLA) Inks Deal With China Lenders for ...,Tesla (TSLA) is likely to benefit from a wholl...,"Tesla, Inc. (TSLA - Free Report) has made the ...",Zacks Investment Research,1,TSLA,0.9928,0.056798,0.097043
2019-03-09,Is This the Final Nail in the Coffin for Tesla...,Elon Musk used to be the solar installer's big...,There were already signs that all was not well...,The Motley Fool,-1,TSLA,0.9965,0.127565,0.095899
2019-03-09,Tesla Has Some Problems,Reading between the lines of the Tesla news ci...,Join Motley Fool analysts Nick Sciple and John...,The Motley Fool,-1,TSLA,0.9999,0.115436,0.107687
2019-03-11,"Stock Market Today: Tesla Plans Price Hikes, P...","Meanwhile, Boeing plummeted following a deadly...",Major stock market indexes climbed on Monday d...,The Motley Fool,-1,TSLA,-0.9235,0.063292,0.087270
...,...,...,...,...,...,...,...,...,...
2019-12-28,Why Your 2020 Resolution Should Be to Buy More...,"After a great 2019 capstone to the 2010s, tech...",After a decade of virtually no returns -- than...,The Motley Fool,1,TSLA,0.9934,0.100860,0.057399
2019-12-29,How Many Vehicles Will Tesla Deliver in Q4?,The company is slated to report its quarterly ...,Sometime this week -- probably on Thursday or ...,The Motley Fool,0,TSLA,0.9880,0.119706,0.023636
2019-12-30,Tesla (TSLA) Rolls Out First Model 3s Built in...,Tesla Motors (TSLA) remains near the peak of i...,"Monday, December 30, 2019\nAdvance Trade in U....",Zacks Investment Research,1,TSLA,-0.8271,0.078244,0.099321
2019-12-30,Tesla to Start Delivery of Model 3 Built at Ch...,The construction of Gigafactory3 in Shanghai i...,"Tesla, Inc. (TSLA - Free Report) will start de...",Zacks Investment Research,0,TSLA,0.9961,0.028692,-0.029774
2019-12-31,Why the Stock Market Soured on Tesla and Centu...,The carmaker's CEO had some Boring news to rep...,Many of us are preparing for the new year and ...,The Motley Fool,-1,TSLA,0.9109,0.087333,0.112693

# Create dataframe for regression grouped on date

In [62]:
df_for_regression_grouped_by_date=pd.DataFrame(df_for_regression.groupby(["date","ticker"]).mean())

In [63]:
df_for_regression_grouped_by_date

,,stocknews_sentiment,vader_sentiment,textblob_lemmatized_sentiments,textblob_stemmed_sentiments
date,ticker,,,,
2019-03-06,TSLA,0.0,0.9726,0.069364,0.041566
2019-03-08,TSLA,1.0,0.9928,0.056798,0.097043
2019-03-09,TSLA,-1.0,0.9982,0.121500,0.101793
2019-03-11,TSLA,-1.0,-0.9235,0.063292,0.087270
2019-03-12,TSLA,-1.0,-0.9229,0.022327,-0.032525
...,...,...,...,...,...
2019-12-27,TSLA,0.5,0.9886,0.149190,0.081275
2019-12-28,TSLA,1.0,0.9934,0.100860,0.057399
2019-12-29,TSLA,0.0,0.9880,0.119706,0.023636
2019-12-30,TSLA,0.5,0.0845,0.053468,0.034774
2019-12-31,TSLA,-1.0,0.9109,0.087333,0.112693

In [64]:
tsla_df

            TSLA_close  TSLA_close_shifted_by_1
date
2019-01-02  310.119995               332.799988
2019-01-03  300.359985               310.119995
2019-01-04  317.690002               300.359985
2019-01-07  334.959991               317.690002
2019-01-08  335.350006               334.959991
...                ...                      ...
2019-12-24  425.250000               419.220001
2019-12-26  430.940002               425.250000
2019-12-27  430.380005               430.940002
2019-12-30  414.700012               430.380005
2019-12-31  418.329987               414.700012

[252 rows x 2 columns]

### ***  _Remember_ - _need to remove row 143

In [65]:
# join tsla_df (stock prices) with df_for_regression
df_for_regression_grouped_by_date=df_for_regression_grouped_by_date.join(tsla_df, on="date")

In [66]:
df_for_regression_grouped_by_date

,,stocknews_sentiment,vader_sentiment,textblob_lemmatized_sentiments,textblob_stemmed_sentiments,TSLA_close,TSLA_close_shifted_by_1
date,ticker,,,,,,
2019-03-06,TSLA,0.0,0.9726,0.069364,0.041566,276.239990,276.540009
2019-03-08,TSLA,1.0,0.9928,0.056798,0.097043,284.140015,276.589996
2019-03-09,TSLA,-1.0,0.9982,0.121500,0.101793,NaN,NaN
2019-03-11,TSLA,-1.0,-0.9235,0.063292,0.087270,290.920013,284.140015
2019-03-12,TSLA,-1.0,-0.9229,0.022327,-0.032525,283.359985,290.920013
...,...,...,...,...,...,...,...
2019-12-27,TSLA,0.5,0.9886,0.149190,0.081275,430.380005,430.940002
2019-12-28,TSLA,1.0,0.9934,0.100860,0.057399,NaN,NaN
2019-12-29,TSLA,0.0,0.9880,0.119706,0.023636,NaN,NaN
2019-12-30,TSLA,0.5,0.0845,0.053468,0.034774,414.700012,430.380005
2019-12-31,TSLA,-1.0,0.9109,0.087333,0.112693,418.329987,414.700012

In [67]:
#just re-sorting the columns
df_for_regression_grouped_by_date= df_for_regression_grouped_by_date[['TSLA_close','TSLA_close_shifted_by_1','stocknews_sentiment', 'vader_sentiment','textblob_lemmatized_sentiments', 'textblob_stemmed_sentiments']]

In [68]:
df_for_regression_grouped_by_date=df_for_regression_grouped_by_date.dropna()

In [69]:
df_for_regression_grouped_by_date

,,TSLA_close,TSLA_close_shifted_by_1,stocknews_sentiment,vader_sentiment,textblob_lemmatized_sentiments,textblob_stemmed_sentiments
date,ticker,,,,,,
2019-03-06,TSLA,276.239990,276.540009,0.000000,0.972600,0.069364,0.041566
2019-03-08,TSLA,284.140015,276.589996,1.000000,0.992800,0.056798,0.097043
2019-03-11,TSLA,290.920013,284.140015,-1.000000,-0.923500,0.063292,0.087270
2019-03-12,TSLA,283.359985,290.920013,-1.000000,-0.922900,0.022327,-0.032525
2019-03-13,TSLA,288.959991,283.359985,1.000000,-0.584900,0.078589,0.042094
...,...,...,...,...,...,...,...
2019-12-24,TSLA,425.250000,419.220001,0.500000,0.989400,0.060742,0.001386
2019-12-26,TSLA,430.940002,425.250000,0.666667,0.997667,0.136902,0.103983
2019-12-27,TSLA,430.380005,430.940002,0.500000,0.988600,0.149190,0.081275
2019-12-30,TSLA,414.700012,430.380005,0.500000,0.084500,0.053468,0.034774
2019-12-31,TSLA,418.329987,414.700012,-1.000000,0.910900,0.087333,0.112693

In [70]:
df_for_regression_grouped_by_date.to_csv('./data/df_for_regression_grouped_by_date.csv',  header=df_for_regression_grouped_by_date.columns)

# Create dataframe for regression grouped on date, source

In [72]:
df_for_regression_grouped_by_date_and_source=pd.DataFrame(df_for_regression.groupby(["date","ticker","source_name"]).mean())

In [77]:
df_for_regression_grouped_by_date_and_source.reset_index(inplace=True)

In [78]:
# Make source_name values little shorter
df_for_regression_grouped_by_date_and_source['source_name'] = df_for_regression_grouped_by_date_and_source['source_name'].replace(['The Motley Fool'],'Motley')

In [80]:
df_for_regression_grouped_by_date_and_source['source_name'] = df_for_regression_grouped_by_date_and_source['source_name'].replace(['Zacks Investment Research'],'Zacks')

In [81]:
df_for_regression_grouped_by_date_and_source

,date,ticker,source_name,stocknews_sentiment,vader_sentiment,textblob_lemmatized_sentiments,textblob_stemmed_sentiments
0,2019-03-06,TSLA,Motley,0.0,0.9726,0.069364,0.041566
1,2019-03-08,TSLA,Zacks,1.0,0.9928,0.056798,0.097043
2,2019-03-09,TSLA,Motley,-1.0,0.9982,0.121500,0.101793
3,2019-03-11,TSLA,Motley,-1.0,-0.9235,0.063292,0.087270
4,2019-03-12,TSLA,Motley,-1.0,-0.9229,0.022327,-0.032525
...,...,...,...,...,...,...,...
195,2019-12-27,TSLA,Zacks,1.0,0.9938,0.151768,0.110277
196,2019-12-28,TSLA,Motley,1.0,0.9934,0.100860,0.057399
197,2019-12-29,TSLA,Motley,0.0,0.9880,0.119706,0.023636
198,2019-12-30,TSLA,Zacks,0.5,0.0845,0.053468,0.034774
199,2019-12-31,TSLA,Motley,-1.0,0.9109,0.087333,0.112693

##  Create temp dataframes for Motley and Zacks. Rename coulmns to respective names and merge again. The final dateframe should have columns as given below
### -->
        ticker','zacks_stocknews_sentiment', 'zacks_vader_sentiment',
       'zacks_textblob_lemmatized_sentiments',
       'zacks_textblob_stemmed_sentiments', 'motley_stocknews_sentiment',
       'motley_vader_sentiment', 'motley_textblob_lemmatized_sentiments',
       'motley_textblob_stemmed_sentiments' ]

In [115]:
# create Motley dataframe
df_for_regression_grouped_by_date_and_source_otley=df_for_regression_grouped_by_date_and_source[df_for_regression_grouped_by_date_and_source.source_name =="Motley"]

In [116]:
df_for_regression_grouped_by_date_and_source_motley.head(2)

,date,ticker,source_name,stocknews_sentiment,vader_sentiment,textblob_lemmatized_sentiments,textblob_stemmed_sentiments
0,2019-03-06,TSLA,Motley,0.0,0.9726,0.069364,0.041566
2,2019-03-09,TSLA,Motley,-1.0,0.9982,0.121500,0.101793

In [117]:
df_for_regression_grouped_by_date_and_source_motley = df_for_regression_grouped_by_date_and_source_motley.drop('source_name', 1)
df_for_regression_grouped_by_date_and_source_motley = df_for_regression_grouped_by_date_and_source_motley.drop('ticker', 1)

In [118]:
df_for_regression_grouped_by_date_and_source_motley.columns = ['date', 'motley_stocknews_sentiment', 'motley_vader_sentiment',
       'motley_textblob_lemmatized_sentiments', 'motley_textblob_stemmed_sentiments']

In [119]:
df_for_regression_grouped_by_date_and_source_motley.head(2)

,date,motley_stocknews_sentiment,motley_vader_sentiment,motley_textblob_lemmatized_sentiments,motley_textblob_stemmed_sentiments
0,2019-03-06,0.0,0.9726,0.069364,0.041566
2,2019-03-09,-1.0,0.9982,0.121500,0.101793

In [120]:
# do the same for Zacks
df_for_regression_grouped_by_date_and_source_zacks=df_for_regression_grouped_by_date_and_source[df_for_regression_grouped_by_date_and_source.source_name =="Zacks"]
df_for_regression_grouped_by_date_and_source_zacks.head(2)

,date,ticker,source_name,stocknews_sentiment,vader_sentiment,textblob_lemmatized_sentiments,textblob_stemmed_sentiments
1,2019-03-08,TSLA,Zacks,1.0,0.9928,0.056798,0.097043
16,2019-04-02,TSLA,Zacks,-1.0,0.9968,-0.069765,-0.154898

In [121]:
df_for_regression_grouped_by_date_and_source_zacks = df_for_regression_grouped_by_date_and_source_zacks.drop('source_name', 1)
df_for_regression_grouped_by_date_and_source_zacks = df_for_regression_grouped_by_date_and_source_zacks.drop('ticker', 1)
df_for_regression_grouped_by_date_and_source_zacks.columns = ['date',  'zacks_stocknews_sentiment', 'zacks_vader_sentiment',
       'zacks_textblob_lemmatized_sentiments', 'zacks_textblob_stemmed_sentiments']
df_for_regression_grouped_by_date_and_source_zacks.head(2)

,date,zacks_stocknews_sentiment,zacks_vader_sentiment,zacks_textblob_lemmatized_sentiments,zacks_textblob_stemmed_sentiments
1,2019-03-08,1.0,0.9928,0.056798,0.097043
16,2019-04-02,-1.0,0.9968,-0.069765,-0.154898

In [122]:
# Set indexes on the above data frames and merge them.
df_for_regression_grouped_by_date_and_source_motley.set_index("date", inplace=True)
df_for_regression_grouped_by_date_and_source_motley.head(2)

,motley_stocknews_sentiment,motley_vader_sentiment,motley_textblob_lemmatized_sentiments,motley_textblob_stemmed_sentiments
date,,,,
2019-03-06,0.0,0.9726,0.069364,0.041566
2019-03-09,-1.0,0.9982,0.121500,0.101793

In [123]:
df_for_regression_grouped_by_date_and_source_zacks.set_index("date", inplace=True)
df_for_regression_grouped_by_date_and_source_zacks.head(2)

,zacks_stocknews_sentiment,zacks_vader_sentiment,zacks_textblob_lemmatized_sentiments,zacks_textblob_stemmed_sentiments
date,,,,
2019-03-08,1.0,0.9928,0.056798,0.097043
2019-04-02,-1.0,0.9968,-0.069765,-0.154898

In [135]:
df_for_regression_grouped_by_date_and_source_transposed = df_for_regression_grouped_by_date_and_source_zacks.join(df_for_regression_grouped_by_date_and_source_motley,on="date")
df_for_regression_grouped_by_date_and_source_transposed.head(4)

,zacks_stocknews_sentiment,zacks_vader_sentiment,zacks_textblob_lemmatized_sentiments,zacks_textblob_stemmed_sentiments,motley_stocknews_sentiment,motley_vader_sentiment,motley_textblob_lemmatized_sentiments,motley_textblob_stemmed_sentiments
date,,,,,,,,
2019-03-08,1.000000,0.992800,0.056798,0.097043,NaN,NaN,NaN,NaN
2019-04-02,-1.000000,0.996800,-0.069765,-0.154898,0.000000,-0.4037,0.077399,0.06403
2019-04-04,-0.333333,-0.255867,0.025594,0.042549,-0.333333,0.1181,0.075108,0.11754
2019-04-08,0.000000,0.962700,0.042437,0.005014,NaN,NaN,NaN,NaN

In [136]:
df_for_regression_grouped_by_date_and_source_transposed["ticker"]="TSLA"

In [138]:
df_for_regression_grouped_by_date_and_source_transposed = df_for_regression_grouped_by_date_and_source_transposed[['ticker','zacks_stocknews_sentiment', 'zacks_vader_sentiment',
       'zacks_textblob_lemmatized_sentiments',
       'zacks_textblob_stemmed_sentiments', 'motley_stocknews_sentiment',
       'motley_vader_sentiment', 'motley_textblob_lemmatized_sentiments',
       'motley_textblob_stemmed_sentiments' ]]

In [140]:
df_for_regression_grouped_by_date_and_source_transposed.head(4)

,ticker,zacks_stocknews_sentiment,zacks_vader_sentiment,zacks_textblob_lemmatized_sentiments,zacks_textblob_stemmed_sentiments,motley_stocknews_sentiment,motley_vader_sentiment,motley_textblob_lemmatized_sentiments,motley_textblob_stemmed_sentiments
date,,,,,,,,,
2019-03-08,TSLA,1.000000,0.992800,0.056798,0.097043,NaN,NaN,NaN,NaN
2019-04-02,TSLA,-1.000000,0.996800,-0.069765,-0.154898,0.000000,-0.4037,0.077399,0.06403
2019-04-04,TSLA,-0.333333,-0.255867,0.025594,0.042549,-0.333333,0.1181,0.075108,0.11754
2019-04-08,TSLA,0.000000,0.962700,0.042437,0.005014,NaN,NaN,NaN,NaN

In [141]:
# join tsla_df (stock prices) with df_for_regression_grouped_by_date_and_source_transposed
df_for_regression_grouped_by_date_and_source_transposed=df_for_regression_grouped_by_date_and_source_transposed.join(tsla_df, on="date")

In [142]:
df_for_regression_grouped_by_date_and_source_transposed

,ticker,zacks_stocknews_sentiment,zacks_vader_sentiment,zacks_textblob_lemmatized_sentiments,zacks_textblob_stemmed_sentiments,motley_stocknews_sentiment,motley_vader_sentiment,motley_textblob_lemmatized_sentiments,motley_textblob_stemmed_sentiments,TSLA_close,TSLA_close_shifted_by_1
date,,,,,,,,,,,
2019-03-08,TSLA,1.000000,0.992800,0.056798,0.097043,NaN,NaN,NaN,NaN,284.140015,276.589996
2019-04-02,TSLA,-1.000000,0.996800,-0.069765,-0.154898,0.000000,-0.4037,0.077399,0.064030,285.880005,289.179993
2019-04-04,TSLA,-0.333333,-0.255867,0.025594,0.042549,-0.333333,0.1181,0.075108,0.117540,267.779999,291.809998
2019-04-08,TSLA,0.000000,0.962700,0.042437,0.005014,NaN,NaN,NaN,NaN,273.200012,274.959991
2019-04-09,TSLA,-1.000000,0.991300,0.038211,0.022396,NaN,NaN,NaN,NaN,272.309998,273.200012
...,...,...,...,...,...,...,...,...,...,...,...
2019-11-27,TSLA,0.000000,0.999500,0.130545,0.083123,0.000000,0.9976,0.166857,0.113449,331.290009,328.920013
2019-12-24,TSLA,0.500000,0.989400,0.060742,0.001386,NaN,NaN,NaN,NaN,425.250000,419.220001
2019-12-26,TSLA,0.666667,0.997667,0.136902,0.103983,NaN,NaN,NaN,NaN,430.940002,425.250000
2019-12-27,TSLA,1.000000,0.993800,0.151768,0.110277,0.000000,0.9834,0.146612,0.052273,430.380005,430.940002
2019-12-30,TSLA,0.500000,0.084500,0.053468,0.034774,NaN,NaN,NaN,NaN,414.700012,430.380005

In [144]:
#just re-sorting the columns
df_for_regression_grouped_by_date_and_source_transposed= df_for_regression_grouped_by_date_and_source_transposed[['ticker', 'TSLA_close','TSLA_close_shifted_by_1','zacks_stocknews_sentiment', 'zacks_vader_sentiment',
       'zacks_textblob_lemmatized_sentiments',
       'zacks_textblob_stemmed_sentiments', 'motley_stocknews_sentiment',
       'motley_vader_sentiment', 'motley_textblob_lemmatized_sentiments',
       'motley_textblob_stemmed_sentiments']]

In [145]:
df_for_regression_grouped_by_date_and_source_transposed

,ticker,TSLA_close,TSLA_close_shifted_by_1,zacks_stocknews_sentiment,zacks_vader_sentiment,zacks_textblob_lemmatized_sentiments,zacks_textblob_stemmed_sentiments,motley_stocknews_sentiment,motley_vader_sentiment,motley_textblob_lemmatized_sentiments,motley_textblob_stemmed_sentiments
date,,,,,,,,,,,
2019-03-08,TSLA,284.140015,276.589996,1.000000,0.992800,0.056798,0.097043,NaN,NaN,NaN,NaN
2019-04-02,TSLA,285.880005,289.179993,-1.000000,0.996800,-0.069765,-0.154898,0.000000,-0.4037,0.077399,0.064030
2019-04-04,TSLA,267.779999,291.809998,-0.333333,-0.255867,0.025594,0.042549,-0.333333,0.1181,0.075108,0.117540
2019-04-08,TSLA,273.200012,274.959991,0.000000,0.962700,0.042437,0.005014,NaN,NaN,NaN,NaN
2019-04-09,TSLA,272.309998,273.200012,-1.000000,0.991300,0.038211,0.022396,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2019-11-27,TSLA,331.290009,328.920013,0.000000,0.999500,0.130545,0.083123,0.000000,0.9976,0.166857,0.113449
2019-12-24,TSLA,425.250000,419.220001,0.500000,0.989400,0.060742,0.001386,NaN,NaN,NaN,NaN
2019-12-26,TSLA,430.940002,425.250000,0.666667,0.997667,0.136902,0.103983,NaN,NaN,NaN,NaN
2019-12-27,TSLA,430.380005,430.940002,1.000000,0.993800,0.151768,0.110277,0.000000,0.9834,0.146612,0.052273
2019-12-30,TSLA,414.700012,430.380005,0.500000,0.084500,0.053468,0.034774,NaN,NaN,NaN,NaN

In [146]:
# save to file with NaN values
df_for_regression_grouped_by_date_and_source_transposed.to_csv('./data/df_for_regression_grouped_by_date_and_source_transposed_with_NaN.csv',  header=df_for_regression_grouped_by_date_and_source_transposed.columns)

In [147]:
# dropna and save dataframe
df_for_regression_grouped_by_date_and_source_transposed=df_for_regression_grouped_by_date_and_source_transposed.dropna()

In [148]:
df_for_regression_grouped_by_date_and_source_transposed.to_csv('./data/df_for_regression_grouped_by_date_and_source_transposed_without_NaN.csv',  header=df_for_regression_grouped_by_date_and_source_transposed.columns)

In [149]:
df_for_regression_grouped_by_date_and_source_transposed

,ticker,TSLA_close,TSLA_close_shifted_by_1,zacks_stocknews_sentiment,zacks_vader_sentiment,zacks_textblob_lemmatized_sentiments,zacks_textblob_stemmed_sentiments,motley_stocknews_sentiment,motley_vader_sentiment,motley_textblob_lemmatized_sentiments,motley_textblob_stemmed_sentiments
date,,,,,,,,,,,
2019-04-02,TSLA,285.880005,289.179993,-1.000000,0.996800,-0.069765,-0.154898,0.000000,-0.403700,0.077399,0.064030
2019-04-04,TSLA,267.779999,291.809998,-0.333333,-0.255867,0.025594,0.042549,-0.333333,0.118100,0.075108,0.117540
2019-04-11,TSLA,268.420013,276.059998,0.000000,0.610100,0.045378,0.041062,-1.000000,0.473150,0.039020,0.055446
2019-04-17,TSLA,271.230011,273.359985,-1.000000,0.997400,0.072517,0.028313,0.000000,0.992900,0.151642,0.083601
2019-04-18,TSLA,273.260010,271.230011,-1.000000,0.670500,-0.025000,0.030000,1.000000,0.995900,0.177291,0.197333
2019-04-22,TSLA,262.750000,273.260010,0.000000,0.690800,0.100000,0.100000,1.000000,0.998600,0.171422,0.157693
2019-05-02,TSLA,244.100006,234.009995,0.500000,0.992000,0.104133,0.091584,1.000000,0.988550,0.119998,0.107060
2019-05-03,TSLA,255.029999,244.100006,-0.500000,0.996850,0.070851,0.043003,1.000000,0.989050,0.133985,0.104487
2019-05-07,TSLA,247.059998,255.339996,0.000000,0.938200,0.195278,0.186667,0.666667,0.994833,0.079418,0.085062
2019-06-10,TSLA,212.880005,204.500000,0.000000,0.913200,0.028138,-0.012055,-1.000000,0.945100,-0.066970,-0.176282
2019-06-20,TSLA,219.619995,226.429993,1.000000,0.996900,0.095075,0.095633,-1.000000,0.940300,0.032064,0.024530
2019-07-02,TSLA,224.550003,227.169998,1.000000,0.993600,0.084587,0.101111,1.000000,0.980750,0.125353,0.079975
2019-07-03,TSLA,234.899994,224.550003,1.000000,0.998000,0.128531,0.084166,1.000000,0.970967,0.119795,0.148874
2019-07-22,TSLA,255.679993,258.179993,0.000000,0.943200,-0.000354,-0.013687,0.000000,0.976800,0.091111,0.044252
2019-07-23,TSLA,260.170013,255.679993,1.000000,0.994800,0.151612,0.177731,0.500000,0.998000,0.140873,0.111523
2019-07-24,TSLA,264.880005,260.170013,-0.500000,0.981450,0.050798,0.014719,1.000000,0.984200,0.130335,0.035536
2019-07-25,TSLA,228.820007,264.880005,-0.666667,0.529667,0.042281,0.056327,-1.000000,0.867700,0.130357,0.075000
2019-08-23,TSLA,211.399994,222.149994,-1.000000,0.940100,0.002629,0.004762,1.000000,0.999900,0.124101,0.123326
2019-08-27,TSLA,214.080002,215.000000,0.000000,0.867100,0.015533,-0.054692,0.000000,0.976500,0.093700,0.111744
2019-09-04,TSLA,220.679993,225.009995,1.000000,0.986600,0.048324,0.011196,1.000000,-0.981000,0.040758,0.007261
2019-09-25,TSLA,228.699997,223.210007,0.000000,0.998700,0.164100,0.140077,0.500000,0.993050,0.112185,0.069313
2019-09-27,TSLA,242.130005,242.559998,0.000000,0.992950,0.053572,0.054752,1.000000,0.989200,0.174517,0.087430
2019-10-03,TSLA,233.029999,243.130005,0.333333,0.997000,0.071564,0.083897,0.000000,0.833500,0.089166,0.111584
2019-10-04,TSLA,231.429993,233.029999,0.000000,0.991400,0.020992,-0.062039,-1.000000,0.971600,0.180963,0.136589
2019-10-22,TSLA,255.580002,253.500000,0.750000,0.987725,0.098178,0.072777,1.000000,0.995200,0.095309,0.113849
2019-10-23,TSLA,254.679993,255.580002,0.500000,0.991400,0.057508,-0.010293,1.000000,0.993500,0.101928,0.107211
2019-10-24,TSLA,299.679993,254.679993,0.333333,0.997467,0.112458,0.117834,1.000000,0.990900,0.184632,0.210714
2019-10-30,TSLA,315.010010,316.220001,0.500000,0.991050,0.117819,0.104724,0.500000,0.986200,0.057677,0.071801
2019-10-31,TSLA,314.920013,315.010010,0.000000,0.997700,0.026327,0.057552,1.000000,0.996150,0.082860,0.083290
2019-11-11,TSLA,345.089996,337.140015,0.000000,0.998300,0.139818,0.081420,1.000000,0.991800,0.121534,0.151818
2019-11-22,TSLA,333.040009,354.829987,0.500000,0.963950,0.083865,0.056052,-1.000000,0.957150,0.101224,0.059535
2019-11-25,TSLA,336.339996,333.040009,0.000000,0.997800,0.105076,0.090551,1.000000,0.531250,0.250284,0.164944
2019-11-26,TSLA,328.920013,336.339996,0.333333,0.983267,0.082331,0.035998,1.000000,0.909400,0.035446,-0.003116
2019-11-27,TSLA,331.290009,328.920013,0.000000,0.999500,0.130545,0.083123,0.000000,0.997600,0.166857,0.113449
2019-12-27,TSLA,430.380005,430.940002,1.000000,0.993800,0.151768,0.110277,0.000000,0.983400,0.146612,0.052273