In [240]:
import pandas as pd

In [241]:
TSLA_yr2019News_FullArtciles_df = pd.read_csv('./data/TSLA_yr2019News_FullArtciles_df.csv')

In [242]:
TSLA_yr2019News_FullArtciles_df.tail(2)

,Unnamed: 0,news_url,image_url,title,text,source_name,date,topics,sentiment,type,tickers,full_text
288,288,https://www.zacks.com/stock/news/619555/tesla-...,https://cdn.snapi.dev/images/v1/o/j/tes723-5.jpg,Tesla (TSLA) to Open First European Gigafactor...,Car production in Tesla's (TSLA) Berlin Gigafa...,Zacks Investment Research,14 Nov 2019,[],Neutral,Article,['TSLA'],Tesla ’s (TSLA - Free Report) electric revolut...
289,289,https://www.fool.com/investing/2019/11/13/here...,https://cdn.snapi.dev/images/v1/n/f/105762111-...,Here's Why Tesla Bears Should Be Concerned,It's understandable if bears are getting worri...,The Motley Fool,13 Nov 2019,[],Negative,Article,['TSLA'],Tesla (NASDAQ:TSLA) bears have reason to worry...

In [243]:
# create custom df from the main df
TSLA_Custom_df=  TSLA_yr2019News_FullArtciles_df[['date', 'title', 'text','full_text',
       'source_name', 'sentiment', 'tickers']]

In [244]:
# replace sentiment column values with new value set
sentiment_map = {"Positive": 1, "Negative": -1, "Neutral": 0}
TSLA_Custom_df["sentiment"].replace(sentiment_map, inplace=True)

C:\Users\JATIN\anaconda3\lib\site-packages\pandas\core\generic.py:6746: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

In [245]:
TSLA_Custom_df.head(2)

,date,title,text,full_text,source_name,sentiment,tickers
0,31 Dec 2019,Why the Stock Market Soured on Tesla and Centu...,The carmaker's CEO had some Boring news to rep...,Many of us are preparing for the new year and ...,The Motley Fool,-1,"['CTL', 'TSLA']"
1,30 Dec 2019,Tesla to Start Delivery of Model 3 Built at Ch...,The construction of Gigafactory3 in Shanghai i...,"Tesla, Inc. (TSLA - Free Report) will start de...",Zacks Investment Research,0,['TSLA']

In [246]:
# change data type of date column and set it as index
TSLA_Custom_df = TSLA_Custom_df.astype({"date": 'datetime64'})
TSLA_Custom_df.set_index("date", inplace=True)

In [247]:
TSLA_Custom_df

,title,text,full_text,source_name,sentiment,tickers
date,,,,,,
2019-12-31,Why the Stock Market Soured on Tesla and Centu...,The carmaker's CEO had some Boring news to rep...,Many of us are preparing for the new year and ...,The Motley Fool,-1,"['CTL', 'TSLA']"
2019-12-30,Tesla to Start Delivery of Model 3 Built at Ch...,The construction of Gigafactory3 in Shanghai i...,"Tesla, Inc. (TSLA - Free Report) will start de...",Zacks Investment Research,0,['TSLA']
2019-12-30,Tesla (TSLA) Rolls Out First Model 3s Built in...,Tesla Motors (TSLA) remains near the peak of i...,"Monday, December 30, 2019\nAdvance Trade in U....",Zacks Investment Research,1,['TSLA']
2019-12-29,How Many Vehicles Will Tesla Deliver in Q4?,The company is slated to report its quarterly ...,Sometime this week -- probably on Thursday or ...,The Motley Fool,0,['TSLA']
2019-12-28,Why Your 2020 Resolution Should Be to Buy More...,"After a great 2019 capstone to the 2010s, tech...",After a decade of virtually no returns -- than...,The Motley Fool,1,"['AMZN', 'GOOG', 'GOOGL', 'MSFT', 'NFLX', 'TSL..."
...,...,...,...,...,...,...
2019-11-16,What We Know About Tesla's Pickup Truck,The electric-car company will finally unveil t...,As if electric-car maker Tesla (NASDAQ:TSLA) i...,The Motley Fool,0,['TSLA']
2019-11-15,"""Consumer Reports"" Now Recommends Tesla's Mode...",The news comes as Tesla aims for record delive...,In a reversal of a previous decision not to re...,The Motley Fool,1,['TSLA']
2019-11-15,3 Stocks That Soared This Earnings Season,Don't miss the stories behind these companies'...,"As usual, earnings season brought with it its ...",The Motley Fool,1,"['AAPL', 'DIS', 'TSLA']"
2019-11-14,Tesla (TSLA) to Open First European Gigafactor...,Car production in Tesla's (TSLA) Berlin Gigafa...,Tesla ’s (TSLA - Free Report) electric revolut...,Zacks Investment Research,0,['TSLA']
2019-11-13,Here's Why Tesla Bears Should Be Concerned,It's understandable if bears are getting worri...,Tesla (NASDAQ:TSLA) bears have reason to worry...,The Motley Fool,-1,['TSLA']

In [248]:
# Because this dataframe contains records related to ticker TSLA only, rename 'tickers' coulmn as 'ticker' and set its value as TSLA for all records
TSLA_Custom_df.rename(columns={"tickers": "ticker"}, inplace=True)
TSLA_Custom_df["ticker"]="TSLA"

# also rename sentiment column to 'stocknews_sentiment' 
TSLA_Custom_df.rename(columns={"sentiment": "stocknews_sentiment"}, inplace=True)

In [249]:
TSLA_Custom_df.head(2)

,title,text,full_text,source_name,stocknews_sentiment,ticker
date,,,,,,
2019-12-31,Why the Stock Market Soured on Tesla and Centu...,The carmaker's CEO had some Boring news to rep...,Many of us are preparing for the new year and ...,The Motley Fool,-1,TSLA
2019-12-30,Tesla to Start Delivery of Model 3 Built at Ch...,The construction of Gigafactory3 in Shanghai i...,"Tesla, Inc. (TSLA - Free Report) will start de...",Zacks Investment Research,0,TSLA

In [250]:
# create dataframe for machine learning grouped by ["date","source_name","ticker"]
ml_df=pd.DataFrame(TSLA_Custom_df.groupby(["date","source_name","ticker"])["stocknews_sentiment"].mean())

In [251]:
ml_df

                                             stocknews_sentiment
date       source_name               ticker
2019-03-06 The Motley Fool           TSLA                    0.0
2019-03-08 Zacks Investment Research TSLA                    1.0
2019-03-09 The Motley Fool           TSLA                   -1.0
2019-03-11 The Motley Fool           TSLA                   -1.0
2019-03-12 The Motley Fool           TSLA                   -1.0
...                                                          ...
2019-12-27 Zacks Investment Research TSLA                    1.0
2019-12-28 The Motley Fool           TSLA                    1.0
2019-12-29 The Motley Fool           TSLA                    0.0
2019-12-30 Zacks Investment Research TSLA                    0.5
2019-12-31 The Motley Fool           TSLA                   -1.0

[200 rows x 1 columns]

In [252]:
ml_df.to_csv('./data/ml_df.csv',  header=ml_df.columns)

In [253]:
# create dataframe for machine learning grouped by ["date","ticker"]
ml_df_stocknews=TSLA_Custom_df

In [254]:
ml_df_stocknews

,title,text,full_text,source_name,stocknews_sentiment,ticker
date,,,,,,
2019-12-31,Why the Stock Market Soured on Tesla and Centu...,The carmaker's CEO had some Boring news to rep...,Many of us are preparing for the new year and ...,The Motley Fool,-1,TSLA
2019-12-30,Tesla to Start Delivery of Model 3 Built at Ch...,The construction of Gigafactory3 in Shanghai i...,"Tesla, Inc. (TSLA - Free Report) will start de...",Zacks Investment Research,0,TSLA
2019-12-30,Tesla (TSLA) Rolls Out First Model 3s Built in...,Tesla Motors (TSLA) remains near the peak of i...,"Monday, December 30, 2019\nAdvance Trade in U....",Zacks Investment Research,1,TSLA
2019-12-29,How Many Vehicles Will Tesla Deliver in Q4?,The company is slated to report its quarterly ...,Sometime this week -- probably on Thursday or ...,The Motley Fool,0,TSLA
2019-12-28,Why Your 2020 Resolution Should Be to Buy More...,"After a great 2019 capstone to the 2010s, tech...",After a decade of virtually no returns -- than...,The Motley Fool,1,TSLA
...,...,...,...,...,...,...
2019-11-16,What We Know About Tesla's Pickup Truck,The electric-car company will finally unveil t...,As if electric-car maker Tesla (NASDAQ:TSLA) i...,The Motley Fool,0,TSLA
2019-11-15,"""Consumer Reports"" Now Recommends Tesla's Mode...",The news comes as Tesla aims for record delive...,In a reversal of a previous decision not to re...,The Motley Fool,1,TSLA
2019-11-15,3 Stocks That Soared This Earnings Season,Don't miss the stories behind these companies'...,"As usual, earnings season brought with it its ...",The Motley Fool,1,TSLA
2019-11-14,Tesla (TSLA) to Open First European Gigafactor...,Car production in Tesla's (TSLA) Berlin Gigafa...,Tesla ’s (TSLA - Free Report) electric revolut...,Zacks Investment Research,0,TSLA
2019-11-13,Here's Why Tesla Bears Should Be Concerned,It's understandable if bears are getting worri...,Tesla (NASDAQ:TSLA) bears have reason to worry...,The Motley Fool,-1,TSLA

In [255]:
ml_df_stocknews.to_csv('./data/ml_df_stocknews.csv',  header=ml_df_stocknews.columns)

In [256]:
## Pull TSLA stock prices and create a dataframe for year 2019

In [257]:
import yfinance as yf

In [258]:
# get TSLA historical market data

tsla_df = yf.download("TSLA", start="2018-12-31", end="2020-01-01")

[*********************100%***********************]  1 of 1 completed

In [259]:
tsla_df=tsla_df[["Close"]]

In [260]:
tsla_df["Close_shifted_by_1"] = tsla_df.Close.shift(1)
tsla_df=tsla_df[tsla_df.index.year == 2019]

C:\Users\JATIN\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [261]:
#tsla_df.columns=['TSLA_Close', 'TSLA_Close_shifted_by_1']

In [262]:
tsla_df.reset_index(inplace=True)
tsla_df.columns

Index(['Date', 'Close', 'Close_shifted_by_1'], dtype='object')

In [263]:
tsla_df.columns=['date','TSLA_close', 'TSLA_close_shifted_by_1']
tsla_df.head(2)

        date  TSLA_close  TSLA_close_shifted_by_1
0 2019-01-02  310.119995               332.799988
1 2019-01-03  300.359985               310.119995

In [264]:
tsla_df.set_index("date", inplace=True)

In [265]:
tsla_df.head(3)

            TSLA_close  TSLA_close_shifted_by_1
date
2019-01-02  310.119995               332.799988
2019-01-03  300.359985               310.119995
2019-01-04  317.690002               300.359985

## Import ml_df_stocknews.csv and create a dataframe for regression analysis. Then import vader sentiments into it.

In [363]:
df_for_regression = pd.read_csv('./data/ml_df_stocknews.csv', parse_dates=True)

In [364]:
df_for_regression.head()

,date,title,text,full_text,source_name,stocknews_sentiment,ticker
0,2019-12-31,Why the Stock Market Soured on Tesla and Centu...,The carmaker's CEO had some Boring news to rep...,Many of us are preparing for the new year and ...,The Motley Fool,-1,TSLA
1,2019-12-30,Tesla to Start Delivery of Model 3 Built at Ch...,The construction of Gigafactory3 in Shanghai i...,"Tesla, Inc. (TSLA - Free Report) will start de...",Zacks Investment Research,0,TSLA
2,2019-12-30,Tesla (TSLA) Rolls Out First Model 3s Built in...,Tesla Motors (TSLA) remains near the peak of i...,"Monday, December 30, 2019\nAdvance Trade in U....",Zacks Investment Research,1,TSLA
3,2019-12-29,How Many Vehicles Will Tesla Deliver in Q4?,The company is slated to report its quarterly ...,Sometime this week -- probably on Thursday or ...,The Motley Fool,0,TSLA
4,2019-12-28,Why Your 2020 Resolution Should Be to Buy More...,"After a great 2019 capstone to the 2010s, tech...",After a decade of virtually no returns -- than...,The Motley Fool,1,TSLA

## Read in Vader, textblob lemmatized sentiments, textblob stemmed sentiments data for the news articlesand create the final dataframe to run regression on.

In [365]:
df_vader_sentiments = pd.read_csv('./data/vader_sentiments.csv',usecols=['Compound'])

In [366]:
df_vader_sentiments.head(3)

   Compound
0    0.9109
1    0.9961
2   -0.8271

In [367]:
df_for_regression["vader_sentiment"] =  list(df_vader_sentiments["Compound"])

In [368]:
df_textblob_lemmatized_sentiments = pd.read_csv('./data/textblob_lemmatized_sentiments.csv',usecols=['full_text'])

In [369]:
df_textblob_lemmatized_sentiments.head(3)

   full_text
0   0.087333
1   0.028692
2   0.078244

In [370]:
df_for_regression["textblob_lemmatized_sentiments"] = list(df_textblob_lemmatized_sentiments["full_text"])

In [371]:
df_textblob_stemmed_sentiments = pd.read_csv('./data/textblob_stemmed_sentiments.csv',usecols=['full_text'])

In [372]:
df_textblob_stemmed_sentiments.head(3)

   full_text
0   0.112693
1  -0.029774
2   0.099321

In [373]:
df_for_regression["textblob_stemmed_sentiments"] = list(df_textblob_stemmed_sentiments["full_text"])

In [374]:
df_for_regression

,date,title,text,full_text,source_name,stocknews_sentiment,ticker,vader_sentiment,textblob_lemmatized_sentiments,textblob_stemmed_sentiments
0,2019-12-31,Why the Stock Market Soured on Tesla and Centu...,The carmaker's CEO had some Boring news to rep...,Many of us are preparing for the new year and ...,The Motley Fool,-1,TSLA,0.9109,0.087333,0.112693
1,2019-12-30,Tesla to Start Delivery of Model 3 Built at Ch...,The construction of Gigafactory3 in Shanghai i...,"Tesla, Inc. (TSLA - Free Report) will start de...",Zacks Investment Research,0,TSLA,0.9961,0.028692,-0.029774
2,2019-12-30,Tesla (TSLA) Rolls Out First Model 3s Built in...,Tesla Motors (TSLA) remains near the peak of i...,"Monday, December 30, 2019\nAdvance Trade in U....",Zacks Investment Research,1,TSLA,-0.8271,0.078244,0.099321
3,2019-12-29,How Many Vehicles Will Tesla Deliver in Q4?,The company is slated to report its quarterly ...,Sometime this week -- probably on Thursday or ...,The Motley Fool,0,TSLA,0.9880,0.119706,0.023636
4,2019-12-28,Why Your 2020 Resolution Should Be to Buy More...,"After a great 2019 capstone to the 2010s, tech...",After a decade of virtually no returns -- than...,The Motley Fool,1,TSLA,0.9934,0.100860,0.057399
...,...,...,...,...,...,...,...,...,...,...
285,2019-11-16,What We Know About Tesla's Pickup Truck,The electric-car company will finally unveil t...,As if electric-car maker Tesla (NASDAQ:TSLA) i...,The Motley Fool,0,TSLA,0.9811,0.075481,0.091288
286,2019-11-15,"""Consumer Reports"" Now Recommends Tesla's Mode...",The news comes as Tesla aims for record delive...,In a reversal of a previous decision not to re...,The Motley Fool,1,TSLA,0.9850,0.193791,0.028636
287,2019-11-15,3 Stocks That Soared This Earnings Season,Don't miss the stories behind these companies'...,"As usual, earnings season brought with it its ...",The Motley Fool,1,TSLA,0.9962,0.174148,0.159366
288,2019-11-14,Tesla (TSLA) to Open First European Gigafactor...,Car production in Tesla's (TSLA) Berlin Gigafa...,Tesla ’s (TSLA - Free Report) electric revolut...,Zacks Investment Research,0,TSLA,0.9947,0.103478,0.091447
289,2019-11-13,Here's Why Tesla Bears Should Be Concerned,It's understandable if bears are getting worri...,Tesla (NASDAQ:TSLA) bears have reason to worry...,The Motley Fool,-1,TSLA,0.9947,0.104454,0.061764

In [375]:
# df_for_regression.reset_index(inplace=True)

In [376]:
df_for_regression=df_for_regression.astype({'date': 'datetime64[ns]'})

In [377]:
df_for_regression.dtypes

date                              datetime64[ns]
title                                     object
text                                      object
full_text                                 object
source_name                               object
stocknews_sentiment                        int64
ticker                                    object
vader_sentiment                          float64
textblob_lemmatized_sentiments           float64
textblob_stemmed_sentiments              float64
dtype: object

In [378]:
df_for_regression.set_index("date", inplace=True)

### remember - _row 143 is invalid, remove it_

In [379]:
df_for_regression["vader_sentiment"][143]

-0.2023

In [380]:
df_for_regression=df_for_regression.sort_values("date", ascending=True)

In [383]:
df_for_regression.head(5)

,title,text,full_text,source_name,stocknews_sentiment,ticker,vader_sentiment,textblob_lemmatized_sentiments,textblob_stemmed_sentiments
date,,,,,,,,,
2019-03-06,Did Audi Just Disrupt Tesla's Model Y?,Audi's e-tron Q4 Concept is aimed squarely at ...,Audi AG (OTC:AUDV.F) took the wraps off its la...,The Motley Fool,0,TSLA,0.9726,0.069364,0.041566
2019-03-08,Tesla (TSLA) Inks Deal With China Lenders for ...,Tesla (TSLA) is likely to benefit from a wholl...,"Tesla, Inc. (TSLA - Free Report) has made the ...",Zacks Investment Research,1,TSLA,0.9928,0.056798,0.097043
2019-03-09,Is This the Final Nail in the Coffin for Tesla...,Elon Musk used to be the solar installer's big...,There were already signs that all was not well...,The Motley Fool,-1,TSLA,0.9965,0.127565,0.095899
2019-03-09,Tesla Has Some Problems,Reading between the lines of the Tesla news ci...,Join Motley Fool analysts Nick Sciple and John...,The Motley Fool,-1,TSLA,0.9999,0.115436,0.107687
2019-03-11,"Stock Market Today: Tesla Plans Price Hikes, P...","Meanwhile, Boeing plummeted following a deadly...",Major stock market indexes climbed on Monday d...,The Motley Fool,-1,TSLA,-0.9235,0.063292,0.087270

In [386]:
df_for_regression_grouped_by_date=pd.DataFrame(df_for_regression.groupby(["date","ticker"]).mean())

In [389]:
df_for_regression_grouped_by_date

,,stocknews_sentiment,vader_sentiment,textblob_lemmatized_sentiments,textblob_stemmed_sentiments
date,ticker,,,,
2019-03-06,TSLA,0.0,0.9726,0.069364,0.041566
2019-03-08,TSLA,1.0,0.9928,0.056798,0.097043
2019-03-09,TSLA,-1.0,0.9982,0.121500,0.101793
2019-03-11,TSLA,-1.0,-0.9235,0.063292,0.087270
2019-03-12,TSLA,-1.0,-0.9229,0.022327,-0.032525
...,...,...,...,...,...
2019-12-27,TSLA,0.5,0.9886,0.149190,0.081275
2019-12-28,TSLA,1.0,0.9934,0.100860,0.057399
2019-12-29,TSLA,0.0,0.9880,0.119706,0.023636
2019-12-30,TSLA,0.5,0.0845,0.053468,0.034774
2019-12-31,TSLA,-1.0,0.9109,0.087333,0.112693

In [390]:
tsla_df

            TSLA_close  TSLA_close_shifted_by_1
date
2019-01-02  310.119995               332.799988
2019-01-03  300.359985               310.119995
2019-01-04  317.690002               300.359985
2019-01-07  334.959991               317.690002
2019-01-08  335.350006               334.959991
...                ...                      ...
2019-12-24  425.250000               419.220001
2019-12-26  430.940002               425.250000
2019-12-27  430.380005               430.940002
2019-12-30  414.700012               430.380005
2019-12-31  418.329987               414.700012

[252 rows x 2 columns]

### ***  _Remember_ - _need to remove row 143

In [393]:
# join tsla_df (stock prices) with df_for_regression
df_for_regression_grouped_by_date=df_for_regression_grouped_by_date.join(tsla_df, on="date")

In [406]:
df_for_regression_grouped_by_date

,,TSLA_close,TSLA_close_shifted_by_1,stocknews_sentiment,vader_sentiment,textblob_lemmatized_sentiments,textblob_stemmed_sentiments
date,ticker,,,,,,
2019-03-06,TSLA,276.239990,276.540009,0.0,0.9726,0.069364,0.041566
2019-03-08,TSLA,284.140015,276.589996,1.0,0.9928,0.056798,0.097043
2019-03-09,TSLA,NaN,NaN,-1.0,0.9982,0.121500,0.101793
2019-03-11,TSLA,290.920013,284.140015,-1.0,-0.9235,0.063292,0.087270
2019-03-12,TSLA,283.359985,290.920013,-1.0,-0.9229,0.022327,-0.032525
...,...,...,...,...,...,...,...
2019-12-27,TSLA,430.380005,430.940002,0.5,0.9886,0.149190,0.081275
2019-12-28,TSLA,NaN,NaN,1.0,0.9934,0.100860,0.057399
2019-12-29,TSLA,NaN,NaN,0.0,0.9880,0.119706,0.023636
2019-12-30,TSLA,414.700012,430.380005,0.5,0.0845,0.053468,0.034774
2019-12-31,TSLA,418.329987,414.700012,-1.0,0.9109,0.087333,0.112693

In [402]:
#just re-sorting the columns
df_for_regression_grouped_by_date= df_for_regression_grouped_by_date[['TSLA_close','TSLA_close_shifted_by_1','stocknews_sentiment', 'vader_sentiment','textblob_lemmatized_sentiments', 'textblob_stemmed_sentiments']]

In [408]:
df_for_regression_grouped_by_date=df_for_regression_grouped_by_date.dropna()

In [409]:
df_for_regression_grouped_by_date

,,TSLA_close,TSLA_close_shifted_by_1,stocknews_sentiment,vader_sentiment,textblob_lemmatized_sentiments,textblob_stemmed_sentiments
date,ticker,,,,,,
2019-03-06,TSLA,276.239990,276.540009,0.000000,0.972600,0.069364,0.041566
2019-03-08,TSLA,284.140015,276.589996,1.000000,0.992800,0.056798,0.097043
2019-03-11,TSLA,290.920013,284.140015,-1.000000,-0.923500,0.063292,0.087270
2019-03-12,TSLA,283.359985,290.920013,-1.000000,-0.922900,0.022327,-0.032525
2019-03-13,TSLA,288.959991,283.359985,1.000000,-0.584900,0.078589,0.042094
...,...,...,...,...,...,...,...
2019-12-24,TSLA,425.250000,419.220001,0.500000,0.989400,0.060742,0.001386
2019-12-26,TSLA,430.940002,425.250000,0.666667,0.997667,0.136902,0.103983
2019-12-27,TSLA,430.380005,430.940002,0.500000,0.988600,0.149190,0.081275
2019-12-30,TSLA,414.700012,430.380005,0.500000,0.084500,0.053468,0.034774
2019-12-31,TSLA,418.329987,414.700012,-1.000000,0.910900,0.087333,0.112693

In [410]:
df_for_regression_grouped_by_date.to_csv('./data/df_for_regression_grouped_by_date.csv',  header=df_for_regression_grouped_by_date.columns)